configure.ac
This issue came up during the package review for Fedora integration.
See https://www.gnu.org/software/libtool/manual/html_node/LT_005fINIT.html
=> AM_PROG_LIBTOOL is obsolete, replace it with LT_INIT

chafa/chafa.c
I need a dry-run chafa command for Debian's autopkgtest infrastructure, which continuously checks whether a package is malfunctional. However currently `chafa --help` and `chafa --version` both return FALSE (1) such that autopkgtest would consider it as an error. This is a false-positive.
Taking gcc as an example
```
$ gcc ; echo $?
gcc: fatal error: no input files
compilation terminated.
1
$ gcc --version ; echo $?
gcc (Debian 8.1.0-9) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
0
$ gcc --help >/dev/null ; echo $?
0
$ 
```
We can see that `gcc --version` doesn't return a failure.
Similar to gcc, this patch makes `chafa …
=> chafa: Return TRUE (0) after print_version().

chafa/chafa-popcnt.c, chafa/chafa-private.h, configure.ac
This avoids "_mm_popcnt_u64" symbol not found error when building chafa
on i386 architecture. However the build system is still not updated, so
one needs to specify -DCHAFA_REG_BIT32 in CFLAGS in order to build chara
on i386 architecture.
Closes: https://github.com/hpjansson/chafa/issues/5
=> Port chafa to i386 architecture. (#5)

README.md
Fixes: https://github.com/hpjansson/chafa/issues/8
=> README: add instruction for apt installation (Debian testing/unstable)

configure.ac
Mention that package "libmagickwand-dev" is needed for build of command line tool on debian.
(needed to do quite some searching to find this so i help it helps anyone)
=> build: Mention dependency for debian

tools/README.md, tools/chafa8x8.py, tools/compare.py, tools/svg2ttf.py
relicensed code under LGPLv3+. I need some time to find the best set of prebuilt font and fix font problems in different terminals. However anyone should be able to generate their custom font with these scripts.
On Debian fontforge doesn't support python3 so svg2ttf.py is for python2.
=> Add python scripts for generating the chafa8x8 font.

tools/fontgen/README.md
There is a small typo in tools/fontgen/README.md.
Should read `research` rather than `reserach`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, reserach -> research

chafa/chafa-term-db.c
st has official 256 color and true color support (https://st.suckless.org/).
This commit adds `st-256color` to the list which also contains `xterm-kitty` and `xterm-256color`
=> Add simpleterminal (st) to 256 compatible list

chafa/chafa-term-db.c
Initially, foot had exactly two terminfos: `foot` and `foot-direct`.
Then, these got upstreamed to ncurses, but with certain non-standard capabilities stripped. Foot has therefore continued to ship the original terminfo files, but under different names.
These are _usually_ called `foot-extra` and `foot-extra-direct`, but the end decision is the distributions’. To handle this, match against `foot` and `foot-*`.
(as suggested in https://github.com/hpjansson/chafa/pull/59#issuecomment-905592238)
=> Open ended matching of foot terminfo names

README
[Scoop](https://github.com/ScoopInstaller/Scoop) is a open source package manager on Windows.  Now scoop can install chafa from the bucket [main](https://github.com/ScoopInstaller/Main) and it uses the official windows download link in https://hpjansson.org/chafa/download/. If it is ok, could you add this installation method to the official website?
=> Add installation method (by scoop) on Windows

.github/workflows/c-cpp.yml
This pull request adds a workflow file for GitHub actions equivalent to [`.travis.yml`](https://github.com/hpjansson/chafa/blob/564376f3e991c4251c844dcdf66b3049cd85a500/.travis.yml) as per #137.
The job is split up into several steps:
1. **Running prerequisites**: Installs build requirements and executes the `LD_LIBRARY_PATH` fix
2. **Making without ImageMagick**: Executes `autogen` with the `--without-imagemagick` flag and makes chafa
3. **Running tests**: Executes `make check`
4. **Making with ImageMagick**: Executes `autogen` without the `--without-imagemagick` flag and makes chafa
5. **Installing chafa**: Runs `sudo make install` and `chafa --version`
6. **Run post install**: Runs the `postinstall.sh` script
7. **After failure**: Cats the test suite log if and only if any of the steps …
=> Migrate build task to GitHub Actions

chafa/chafa-canvas.c
Fix #147 (kind of).
As suggested, I just replaced `P2=1` with `P2=0` while generating Sixel images.
However, this is rather disappointing. Not all terminals seem to support this parameter very well.
Screenshots are more descriptive than words. I configured the terminal with a background when I could.
Layout is:
```
wezterm | konsole | mlterm
--------------------------
xterm  |  zellij |  foot
```
---
`chafa -f sixels -d 1 poke.gif`
`cat poke.sixel`
---
`chafa -f sixels -d 1 poke.gif`
`cat poke.sixel`
---
That looks like an improvement for `foot` but a regression for `wezterm` and `zellij`.
I think `wezterm` supports Kitty protocol, so I assume it will be preferred over Sixel most of the time?
Regarding `zellij`, rendering of GIF is already quite poor because it causes a lot of flickering …
=> Fix Sixel rendering of GIF images with transparency

AUTHORS, configure.ac, tools/chafa/Makefile.am, tools/chafa/jxl-loader.c, tools/chafa/jxl-loader.h, tools/chafa/media-loader.c
Hi !
This PR add [JPEG XL](https://jpegxl.info/) support for chafa using [libjxl](https://github.com/libjxl/libjxl).
I'm not familiar with autotools so I hope the config is correct.
=> Add JPEG XL support.

tools/completions/Makefile.am
`install-zsh-completion` was only added as a phony target, and running `make install-zsh-completion` does nothing.
Fixes this by declaring the target properly.
=> Fix Makefile.am for zsh completion

chafa/chafa-term-db.c
The Eat terminal supports Sixel mode as of version 0.9: : https://www.reddit.com/r/emacs/comments/172vgex/eat_09_released/
The proper way to detect Eat is to look for the EAT_SHELL_INTEGRATION_DIR environment variable:
https://codeberg.org/akib/emacs-eat/src/commit/3a6f418f55d183b9d86f99c140caed4ba3d44f93/eat.el#L6993-L6994
It also sets TERM with the "eat-" prefix, i.e. "eat-truecolor": https://codeberg.org/akib/emacs-eat/src/commit/3a6f418f55d183b9d86f99c140caed4ba3d44f93/eat.el#L4800-L4812
Closes hpjansson/chafa#197.
=> ChafaTermDb: Eat understands sixel graphics

chafa/chafa-term-db.c, tools/chafa/chafa.c
The Eat terminal advertises its color support by setting its TERM to:
* eat-truecolor when it supports more than 256 colors,
* eat-256color when it supports more than 16 colors,
* eat-16color when it supports more than 8 colors,
* eat-color when it supports more than 1 color,
* eat-mono when it supports no colors.
Note that eat-16color isn't actually supported yet, but a bug has been filed upstream: https://codeberg.org/akib/emacs-eat/issues/154
=> ChafaTermDb: Eat advertises color support via TERM

configure.ac
Some code which was only valid using GNU bash was included. Detected in Gentoo packaging via:
```
* QA Notice: Abnormal configure code
*
* ./configure: 17292: test: unexpected operator
```
Bash provides the standard `test XXX = YYY` or `[ XXX = YYY ]` utilities. It also provides the ability to spell the equals sign as a double equals. This does nothing whatsoever -- it adds no new functionality to bash, it forbids nothing, it is *literally* an exact alias.
It should never be used under any circumstances. All developers must immediately forget that it exists. Using it is non-portable and does not work in /bin/sh scripts such as configure scripts, and it results in dangerous muscle memory when used in bash scripts because it makes people unthinkingly use the double equals even in /bin/sh …
=> configure: fix broken bashisms resulting in logic failure

chafa/chafa-canvas.c
I've noticed tons of leaks on `chafa_canvas_print_rows_strv()` according to ASAN. It appears that `chafa_canvas_print_rows()` refs term_info, but never unrefs it.
=> chafa_canvas_print_rows: term_info leak

chafa/chafa-canvas.c, chafa/internal/chafa-iterm2-canvas.c, chafa/internal/chafa-iterm2-canvas.h
This makes the `iterm2` pixel mode consistent with others, especially `kitty`. Running
```
chafa images/images/c.png -f iterm -t 1
```
before and then after produced (the fire-y image in the background is my desktop background):
Fixes #254.
=> Respect `alpha_threshold = 1` in `iterm2` pixel mode

tools/chafa/chafa.c
`--grid` now respects `--exact-size on`, using `CHAFA_TUCK_SHRINK_TO_FIT`.
| before | after |
|--|--|
| ![Screenshot_2025-04-23_09-30-19](https://github.com/user-attachments/assets/f48f08f5-2dce-4643-aa18-41b1a0240c71) | ![Screenshot_2025-04-23_09-33-20](https://github.com/user-attachments/assets/b8456cb0-ef73-4f96-9525-add1bda37761) |
Works fine with large images too.
- - -
`--exact-size auto` is still left out, but it's not clear how to go about it since it'll take effect per cell.
=> Respect `--exact-size on` in grid layout

chafa/chafa-canvas.c, chafa/internal/chafa-pixops.c, chafa/internal/chafa-pixops.h, tools/chafa/chafa.c
Implements alignment and tuck for SYMBOLS pixel mode.
| before | after |
|--|--|
| ![Screenshot_2025-04-23_08-14-51](https://github.com/user-attachments/assets/df79e2dd-f601-42f3-b85e-e1ef01d76ecf) | ![Screenshot_2025-04-23_08-13-38](https://github.com/user-attachments/assets/754e8782-a301-49af-aa48-84d21de583a1) |
Fixes #250
This also inherently implements sub-cell scaling for SYMBOLS, as seen below (the grey white strips at the bottom and right edges respectively):
| vertical | horizontal |
|--|--|
| ![Screenshot_2025-04-23_08-35-41](https://github.com/user-attachments/assets/9a6af5a5-26a0-441e-8ec8-d897fe0f0997) | ![Screenshot_2025-04-23_08-38-13](https://github.com/user-attachments/assets/702a6907-6c31-405e-ac41-b40969c85133) |
Though, there seems to be a discrepancy between the …
=> Respect alignment and tuck for SYMBOLS pixel mode

tools/chafa/chafa.c, tools/chafa/grid-layout.c, tools/chafa/grid-layout.h
- Implements intracell alignment for the grid layout i.e `--grid` now respects `--align` within each cell.
- Adds `halign` and `valign` fields to `GridLayout`.
- Adds `grid_layout_set_align()`.
- Defines separate alignment defaults for grid and non-grid layouts.
| before | after |
|--|--|
| ![Screenshot_2025-04-23_08-57-02](https://github.com/user-attachments/assets/ee98839c-9631-4992-9440-275c7e824893) | ![Screenshot_2025-04-23_08-57-44](https://github.com/user-attachments/assets/6a4fa886-78bd-4325-aae6-b462e57a0bcf) |
Resolves #258, while taking https://github.com/hpjansson/chafa/issues/253#issuecomment-2689146225 into consideration.
=> Grid layout intracell alignment

chafa/internal/chafa-passthrough-encoder.c
While compiling chafa with MinGW-w64, this error happened and the build process was broken:
```
/src/chafa-1.16.0/chafa/internal/chafa-passthrough-encoder.c: In function 'chafa_passthrough_encoder_append':
/src/chafa-1.16.0/chafa/internal/chafa-passthrough-encoder.c:163:54: error: implicit declaration of function 'strlen' [-Wimplicit-function-declaration]
163 |     chafa_passthrough_encoder_append_len (ptenc, in, strlen (in));
|                                                      ^~~~~~
/src/chafa-1.16.0/chafa/internal/chafa-passthrough-encoder.c:24:1: note: include '<string.h>' or provide a declaration of 'strlen'
23 | #include "internal/chafa-passthrough-encoder.h"
+++ |+#include <string.h>
24 |
```
Attached patch fixes this error.
=> MinGW: fix undeclared function error for strlen()

Makefile.am
The fix in #294 turned out not to be perfect.
=> build: fix a typo, msudo -> sudo
